# Use Amazon Corretto as the base image with JDK 11
FROM amazoncorretto:11

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Run the Maven build command to package the application
RUN ./mvnw package

# Expose the application port (default for Spring Boot apps is 8080)
EXPOSE 8080

# Set the command to run the application
CMD ["java", "-jar", "target/docker-example-1.1.3.jar"]
