# Use an appropriate Node.js version
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 8080 for the backend
EXPOSE 8080

# Add environment variables for the backend configuration
ENV FRONT_URL=http://localhost:5000

# Start the backend server
CMD ["npm", "start"]
